using System.Globalization;
using System.Text;
using SlayIdleRepeat.Core.Content;

namespace SlayIdleRepeat.Core;

/// <summary>
/// 🔒 `30` §3 — everything ambient, as data. <em>"This is the part that most often gets missed, and
/// it is where 'playable in memory' is actually won or lost."</em>
/// </summary>
/// <remarks>
/// <para>
/// 🔒 The rule that generalises the whole type (`30` §3): <b>if a rule needs to know something
/// about the outside world, that something is an argument, not a call.</b> Five members, and each
/// of them is a value precisely because the alternative is a call:
/// </para>
/// <list type="bullet">
///   <item><b>Time</b> is <see cref="NowUtc"/>, not <c>IClockPort</c>. Energy regeneration, the
///   05:00 UTC daily resets, event windows (`26` §4), guild weeks (`27` §4), PvP seasons
///   (`11` §5.3) and subscription expiry (`12` §2.2) are all time-dependent rules, and a rule that
///   calls a clock is not pure. <c>IClockPort</c> remains — the <b>composition root</b> calls it and
///   puts the answer here. There is deliberately no <c>GameContext.Now()</c>.</item>
///   <item><b>Randomness</b> is <see cref="CommandSeed"/>, and only for meta commands — see its own
///   remarks.</item>
///   <item><b>Content</b> is a version-stamped <see cref="ContentSnapshot"/>. Loading JSON is I/O
///   and belongs in an adapter; <em>reading</em> content is a rule (`14` §6). The stamp is what
///   makes a replayed command reproduce its original outcome after a balance patch.</item>
///   <item><b>Entitlement</b> is a read-only <see cref="Core.Entitlements"/> the server resolved —
///   readable by the ad-grant cap rule alone (`30` §3).</item>
///   <item><b>Feature flags</b> are a resolved <see cref="FeatureFlags"/> value. The domain must
///   not call a config service mid-rule.</item>
/// </list>
/// <para>
/// 🔒 The guards live in the <c>init</c> accessors, not in property initializers, so they run on the
/// <c>with</c> path too. An initializer runs only in the primary constructor; the synthesized copy
/// constructor copies backing fields and then calls the plain <c>init</c> setters, so
/// <c>context with { Content = null! }</c> would otherwise produce a context with a hole — and the
/// guarantee below would be false exactly where nobody was looking.
/// </para>
/// <para>
/// ⚠️ <b>Value equality here is shallow, and the shallowness is stated rather than fixed.</b>
/// <see cref="NowUtc"/> and <see cref="CommandSeed"/> compare by value; <see cref="Content"/>,
/// <see cref="Core.Entitlements"/> and <see cref="Flags"/> declare no equality of their own and so
/// compare <b>by reference</b>. Two contexts describing the same ambience but built from separately
/// constructed members are <em>not</em> equal. <c>Entitlements</c> cannot have value equality at all
/// (see its own remarks), and nothing in the domain compares two contexts. Code that must compare a
/// replayed context against a recorded one compares <c>Content.Version</c> and the flag members
/// explicitly.
/// </para>
/// </remarks>
/// <param name="NowUtc">
/// The instant this command is being applied at, as the composition root read it from
/// <c>IClockPort</c>. A value, never a call (`30` §3). 🔒 Must carry a zero offset — see
/// <c>RequireUtc</c>.
/// </param>
/// <param name="CommandSeed">
/// 🔒 The server-issued per-command seed. <b>Meta commands only — <c>null</c> on every run
/// command</b>, and the nullability is load-bearing (`14` §8.1, `30` §3).
/// <para>
/// Two regimes. <b>In-run draws never touch this.</b> Draw <c>i</c> of stream <c>s</c> is
/// <c>Hash64(runSeed, s, i)</c>, where the <c>Run</c> aggregate holds <c>runSeed</c> and the
/// persisted per-stream counters — both authoritative run state, not ambience. <b>Meta draws</b> —
/// wheel spins, container opens, the <c>BEGIN_SESSION</c> quest and Daily-shop draw — are
/// <c>Hash64(CommandSeed, s, i)</c> with <c>i</c> starting at 0 for each command and no persisted
/// counter; the command is atomic and idempotency replays its stored outcome, so a meta draw can
/// never be re-rolled by resubmission.
/// </para>
/// <para>
/// The seed is generated by the server host and <b>never by the domain</b>: the invariant behind
/// both regimes is that the domain never invents entropy. A non-nullable <c>ulong</c> here would
/// make "no seed" unrepresentable and force the host to invent one for the run commands that must
/// not have one — and <c>0</c> is a legitimate seed, not an absence. The pairing rule — which
/// commands carry a seed — is pinned by <c>CommandSeedPinTests</c> in
/// <c>SlayIdleRepeat.Core.Tests</c>, and has been live over all 49 rows of `14` §2.3 since M1-02:
/// every <c>CommandKind.Run</c> row is refused a seed, and exactly the nine ⚄ meta rows require one.
/// </para>
/// </param>
/// <param name="Content">The loaded, validated, version-stamped content this command reads.</param>
/// <param name="Entitlements">
/// The subscription entitlement the server resolved. Read-only to the domain, and readable at all
/// by exactly one rule (`30` §3).
/// </param>
/// <param name="Flags">The `14` §14 kill switches, resolved at the composition root.</param>
public sealed record GameContext(
    DateTimeOffset NowUtc,
    ulong? CommandSeed,
    ContentSnapshot Content,
    Entitlements Entitlements,
    FeatureFlags Flags)
{
    private readonly DateTimeOffset _nowUtc = RequireUtc(NowUtc);
    private readonly ContentSnapshot _content = Require(Content, nameof(Content));
    private readonly Entitlements _entitlements = Require(Entitlements, nameof(Entitlements));
    private readonly FeatureFlags _flags = Require(Flags, nameof(Flags));

    /// <inheritdoc cref="GameContext(DateTimeOffset, ulong?, ContentSnapshot, Entitlements, FeatureFlags)"
    ///     path="/param[@name='NowUtc']"/>
    public DateTimeOffset NowUtc
    {
        get => _nowUtc;
        init => _nowUtc = RequireUtc(value);
    }

    /// <inheritdoc cref="GameContext(DateTimeOffset, ulong?, ContentSnapshot, Entitlements, FeatureFlags)"
    ///     path="/param[@name='Content']"/>
    public ContentSnapshot Content
    {
        get => _content;
        init => _content = Require(value, nameof(Content));
    }

    /// <inheritdoc cref="GameContext(DateTimeOffset, ulong?, ContentSnapshot, Entitlements, FeatureFlags)"
    ///     path="/param[@name='Entitlements']"/>
    public Entitlements Entitlements
    {
        get => _entitlements;
        init => _entitlements = Require(value, nameof(Entitlements));
    }

    /// <inheritdoc cref="GameContext(DateTimeOffset, ulong?, ContentSnapshot, Entitlements, FeatureFlags)"
    ///     path="/param[@name='Flags']"/>
    public FeatureFlags Flags
    {
        get => _flags;
        init => _flags = Require(value, nameof(Flags));
    }

    /// <summary>
    /// 🔒 Renders the context with <see cref="CultureInfo.InvariantCulture"/> and the round-trip
    /// <c>"O"</c> format, so a context reads the same on a German laptop and in the Linux container.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A record's synthesized <c>PrintMembers</c> appends <see cref="NowUtc"/> through
    /// <c>StringBuilder.Append(object)</c>, which formats with the <em>ambient</em> culture:
    /// <c>12.08.2026 05:00:00 +00:00</c> under <c>de-DE</c> against <c>08/12/2026 …</c> invariant.
    /// The boxing hides that from
    /// <c>AmbientApiTests.Core_and_Application_contain_no_culture_sensitive_formatting</c>, which
    /// matches a call whose declaring type is <c>System.DateTimeOffset</c>. `14` §8.2 wants `Core`
    /// rendering identically everywhere, so it is fixed here rather than left in the one place that
    /// rule cannot see.
    /// </para>
    /// <para>
    /// The entitlement is deliberately <b>not</b> rendered: no diagnostic needs it, and reading it
    /// here would put a read of the Plus flag into a `Core` method for nothing. Content is rendered
    /// as its version stamp, which is the only part of a snapshot that identifies it.
    /// </para>
    /// <para>
    /// <c>private</c>, not <c>protected override</c>: this record is <c>sealed</c>, and the compiler
    /// requires the sealed form of the hook (CS8879).
    /// </para>
    /// </remarks>
    private bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.Append(CultureInfo.InvariantCulture, $"NowUtc = {NowUtc:O}");
        builder.Append(CultureInfo.InvariantCulture, $", CommandSeed = {Describe(CommandSeed)}");
        builder.Append(CultureInfo.InvariantCulture, $", Content = {Content.Version.Short}");
        builder.Append(CultureInfo.InvariantCulture, $", Flags = {Flags.PvpEnabled}/{Flags.PlusOfferEnabled}");

        return true;
    }

    private static string Describe(ulong? commandSeed) =>
        commandSeed?.ToString(CultureInfo.InvariantCulture) ?? "null";

    private static T Require<T>(T value, string parameterName)
        where T : class =>
        value ?? throw new ArgumentNullException(parameterName);

    /// <summary>
    /// 🔒 Refuses an instant that is not stated in UTC. <c>DateTimeOffset</c> keeps its offset, and
    /// every wall-clock rule in the game — the 05:00 UTC daily reset above all — reads components
    /// off this value, so <c>06:00 +02:00</c> and <c>06:00 +00:00</c> are two different game days
    /// while naming instants two hours apart. Normalising silently would hide a miswired adapter;
    /// this names it at the boundary where it was introduced.
    /// </summary>
    private static DateTimeOffset RequireUtc(DateTimeOffset nowUtc) =>
        nowUtc.Offset == TimeSpan.Zero
            ? nowUtc
            : throw new ArgumentException(
                "NowUtc carries a non-zero UTC offset. The 05:00 UTC daily resets, event windows " +
                "and season boundaries read wall-clock components off this value, so a local-offset " +
                "instant rolls the game day early even though it names the same moment. The " +
                "composition root passes IClockPort's UTC answer through unchanged (30 §3).",
                nameof(NowUtc));
}
