using SlayIdleRepeat.Core.Content;

namespace SlayIdleRepeat.Core;

/// <summary>
/// 🔒 `30` §3 — everything ambient, as data. <em>"This is the part that most often gets missed, and
/// it is where 'playable in memory' is actually won or lost."</em>
/// </summary>
/// <remarks>
/// <para>
/// 🔒 The rule that generalises the whole type (`30` §3): <b>if a rule needs to know something
/// about the outside world, that something is an argument, not a call.</b> Five members, and each
/// of them is a value precisely because the alternative is a call:
/// </para>
/// <list type="bullet">
///   <item><b>Time</b> is <see cref="NowUtc"/>, not <c>IClockPort</c>. Energy regeneration, the
///   05:00 UTC daily resets, event windows (`26` §4), guild weeks (`27` §4), PvP seasons
///   (`11` §5.3) and subscription expiry (`12` §2.2) are all time-dependent rules, and a rule that
///   calls a clock is not pure. <c>IClockPort</c> remains — the <b>composition root</b> calls it and
///   puts the answer here. There is deliberately no <c>GameContext.Now()</c>.</item>
///   <item><b>Randomness</b> is <see cref="CommandSeed"/>, and only for meta commands — see its own
///   remarks.</item>
///   <item><b>Content</b> is a version-stamped <see cref="ContentSnapshot"/>. Loading JSON is I/O
///   and belongs in an adapter; <em>reading</em> content is a rule (`14` §6). The stamp is what
///   makes a replayed command reproduce its original outcome after a balance patch.</item>
///   <item><b>Entitlement</b> is a read-only <see cref="Core.Entitlements"/> the server resolved —
///   readable by the ad-grant cap rule alone (`30` §3).</item>
///   <item><b>Feature flags</b> are a resolved <see cref="FeatureFlags"/> record. The domain must
///   not call a config service mid-rule.</item>
/// </list>
/// <para>
/// The three reference members are guarded at construction. A context assembled with a hole fails
/// where the hole was introduced — the composition root — rather than several rules later, in a
/// rule that did nothing wrong.
/// </para>
/// </remarks>
/// <param name="NowUtc">
/// The instant this command is being applied at, as the composition root read it from
/// <c>IClockPort</c>. A value, never a call (`30` §3).
/// </param>
/// <param name="CommandSeed">
/// 🔒 The server-issued per-command seed. <b>Meta commands only — <c>null</c> on every run
/// command</b>, and the nullability is load-bearing (`14` §8.1, `30` §3).
/// <para>
/// Two regimes. <b>In-run draws never touch this.</b> Draw <c>i</c> of stream <c>s</c> is
/// <c>Hash64(runSeed, s, i)</c>, where the <c>Run</c> aggregate holds <c>runSeed</c> and the
/// persisted per-stream counters — both authoritative run state, not ambience. <b>Meta draws</b> —
/// wheel spins, container opens, the <c>BEGIN_SESSION</c> quest and Daily-shop draw — are
/// <c>Hash64(CommandSeed, s, i)</c> with <c>i</c> starting at 0 for each command and no persisted
/// counter; the command is atomic and idempotency replays its stored outcome, so a meta draw can
/// never be re-rolled by resubmission.
/// </para>
/// <para>
/// The seed is generated by the server host and <b>never by the domain</b>: the invariant behind
/// both regimes is that the domain never invents entropy. A non-nullable <c>ulong</c> here would
/// make "no seed" unrepresentable and force the host to invent one for the run commands that must
/// not have one. The pairing rule — which commands carry a seed — is pinned by
/// <c>CommandSeedPinTests</c> in <c>SlayIdleRepeat.Core.Tests</c>, live from the day M1-02 declares
/// the command vocabulary.
/// </para>
/// </param>
/// <param name="Content">The loaded, validated, version-stamped content this command reads.</param>
/// <param name="Entitlements">
/// The subscription entitlement the server resolved. Read-only to the domain, and readable at all
/// by exactly one rule (`30` §3).
/// </param>
/// <param name="Flags">The `14` §14 kill switches, resolved at the composition root.</param>
public sealed record GameContext(
    DateTimeOffset NowUtc,
    ulong? CommandSeed,
    ContentSnapshot Content,
    Entitlements Entitlements,
    FeatureFlags Flags)
{
    /// <inheritdoc cref="GameContext(DateTimeOffset, ulong?, ContentSnapshot, Entitlements, FeatureFlags)"/>
    public ContentSnapshot Content { get; init; } =
        Content ?? throw new ArgumentNullException(nameof(Content));

    /// <inheritdoc cref="GameContext(DateTimeOffset, ulong?, ContentSnapshot, Entitlements, FeatureFlags)"/>
    public Entitlements Entitlements { get; init; } =
        Entitlements ?? throw new ArgumentNullException(nameof(Entitlements));

    /// <inheritdoc cref="GameContext(DateTimeOffset, ulong?, ContentSnapshot, Entitlements, FeatureFlags)"/>
    public FeatureFlags Flags { get; init; } =
        Flags ?? throw new ArgumentNullException(nameof(Flags));
}
