namespace SlayIdleRepeat.AssetProvenance;

/// <summary>The provenance of one delivered asset, keyed to an id in the register.</summary>
/// <remarks>
/// <para>
/// Discriminated by <see cref="Kind"/>, because three sources exist with disjoint field sets: a
/// Midjourney record's job/prompt/seed fields are meaningless for code-drawn output, which has
/// neither, and a CC0 pack has a source, URL and licence instead. A single flat record with every
/// field optional would make "which fields must be present" undecidable.
/// </para>
/// <para>
/// There is deliberately no per-record "licence confirmed" member — that is one fact per tool, not
/// one copy per record. It lives in <see cref="ToolLicence"/> and starts unset; nothing in this
/// assembly defaults it to anything.
/// </para>
/// </remarks>
public abstract record ProvenanceRecord
{
    /// <summary>
    /// The asset id from the register — an <see cref="AssetManifest.ArtAsset.Id"/> or an
    /// <see cref="AssetManifest.AudioAsset.Id"/>. Also the record's file stem in the store.
    /// </summary>
    public required string AssetId { get; init; }

    /// <summary>The audio tool + version, or null. Required on an audio record and forbidden on an art one — see <see cref="AudioTooling"/>.</summary>
    public required AudioTooling? Tooling { get; init; }

    /// <summary>The discriminator, as written in the record's <c>kind</c> member.</summary>
    public abstract string Kind { get; }

    /// <summary>Every generation tool this record names, for the licence check. Empty where the record names none.</summary>
    public abstract IEnumerable<string> ToolsNamed { get; }
}

/// <summary>The tool + version members an audio record carries that an art record has no place for.</summary>
/// <remarks>
/// Required on an audio record, forbidden on an art one: an art record's tool is named by its
/// <see cref="ProvenanceRecord.Kind"/> instead, and a second tool field would be a second source of
/// truth for one fact. <see cref="RecordValidator"/> enforces both directions.
/// </remarks>
/// <param name="Tool">The tool's name, e.g. <c>Audacity</c>.</param>
/// <param name="Version">The tool's version string, verbatim as the tool reports it.</param>
public sealed record AudioTooling(string Tool, string Version);

/// <summary>An asset generated by Midjourney.</summary>
/// <remarks>
/// Every parameter is a <see cref="string"/> rather than a parsed number, including
/// <see cref="Seed"/> and <see cref="Stylize"/> — a provenance record stores what the tool
/// reported, and parsing a value into a number and writing it back would silently normalise it.
/// </remarks>
public sealed record MidjourneyProvenance : ProvenanceRecord
{
    /// <summary>The discriminator value.</summary>
    public const string KindName = "midjourney";

    /// <summary>The job ID.</summary>
    public required string JobId { get; init; }

    /// <summary>The full positive prompt, style scaffold included.</summary>
    public required string Prompt { get; init; }

    /// <summary>The seed, verbatim.</summary>
    public required string Seed { get; init; }

    /// <summary>The <c>--sref</c> style-reference value.</summary>
    public required string Sref { get; init; }

    /// <summary>The <c>--ar</c> value.</summary>
    public required string AspectRatio { get; init; }

    /// <summary>The <c>--style</c> value.</summary>
    public required string Style { get; init; }

    /// <summary>The <c>--s</c> stylize value.</summary>
    public required string Stylize { get; init; }

    /// <summary>The model version the job ran on.</summary>
    public required string ModelVersion { get; init; }

    /// <summary>The date, ISO-8601 <c>YYYY-MM-DD</c>.</summary>
    public required string Date { get; init; }

    /// <inheritdoc/>
    public override string Kind => KindName;

    /// <inheritdoc/>
    public override IEnumerable<string> ToolsNamed =>
        Tooling is null ? [KindName] : [KindName, Tooling.Tool];
}

/// <summary>Code-drawn output: placeholder generation, and procedural in-engine effects that replaced some cut art rows.</summary>
/// <remarks>
/// <see cref="RepoCommit"/> stands in for a job id and seed: for code-drawn art the reproducibility
/// anchor is the revision of the generator, not a job that never ran.
/// </remarks>
public sealed record ProceduralProvenance : ProvenanceRecord
{
    /// <summary>The discriminator value.</summary>
    public const string KindName = "procedural";

    /// <summary>The generator that drew it, e.g. a tool assembly name.</summary>
    public required string Generator { get; init; }

    /// <summary>The full 40-hex commit of this repository at the time it was drawn.</summary>
    public required string RepoCommit { get; init; }

    /// <summary>The generator's parameters. May be empty; may not be null.</summary>
    public required IReadOnlyDictionary<string, string> Parameters { get; init; }

    /// <inheritdoc/>
    public override string Kind => KindName;

    /// <summary>Empty for a procedural art record: the "tool" is this repository, which needs no commercial licence.</summary>
    public override IEnumerable<string> ToolsNamed =>
        Tooling is null ? [] : [Tooling.Tool];
}

/// <summary>A CC0 asset taken from a library.</summary>
public sealed record Cc0Provenance : ProvenanceRecord
{
    /// <summary>The discriminator value.</summary>
    public const string KindName = "cc0";

    /// <summary>The pack or library it came from.</summary>
    public required string Source { get; init; }

    /// <summary>The URL it was retrieved from.</summary>
    public required string Url { get; init; }

    /// <summary>The licence text or SPDX identifier, e.g. <c>CC0-1.0</c>.</summary>
    public required string Licence { get; init; }

    /// <summary>The retrieval date, ISO-8601 <c>YYYY-MM-DD</c>.</summary>
    public required string DateRetrieved { get; init; }

    /// <inheritdoc/>
    public override string Kind => KindName;

    /// <summary>The pack itself is not a generation tool — its terms are <see cref="Licence"/>. Only an editing tool, where used, needs a licence confirmation.</summary>
    public override IEnumerable<string> ToolsNamed =>
        Tooling is null ? [] : [Tooling.Tool];
}
