namespace SlayIdleRepeat.AssetProvenance;

/// <summary>
/// The provenance of one delivered asset, keyed to an id in M8-09's register.
/// </summary>
/// <remarks>
/// <para>
/// 🔒 <b>Discriminated by <see cref="Kind"/>, because three sources exist and `15` §B0's field
/// set fits exactly one of them.</b> §B0 tabulates job id, prompt, seed, <c>--sref</c>,
/// <c>--ar</c>/<c>--style</c>/<c>--s</c> and date — every one of which is meaningless for
/// code-drawn output (M8-10's placeholders have no seed and no job) and for a CC0 pack (which has
/// a source, a URL and a licence instead). A single flat record with all three field sets
/// optional would make "which fields must be present" undecidable, which is the one question a
/// legal prerequisite has to be able to answer.
/// </para>
/// <para>
/// <b>There is deliberately no per-record "licence confirmed" member.</b> `15` §G and `20` §6 ask
/// for the commercial licence of each <em>tool</em> to be confirmed in writing — one fact per
/// tool, not 1,080 copies of it. It lives in <see cref="ToolLicence"/>, it starts
/// <b>unset</b> (M8 kickoff 2026-08-12: the written confirmation is M8-01b, a legal act the
/// product owner owns), and nothing in this assembly defaults it to anything.
/// </para>
/// </remarks>
public abstract record ProvenanceRecord
{
    /// <summary>
    /// The asset id from M8-09's register — an <see cref="AssetManifest.ArtAsset.Id"/> or an
    /// <see cref="AssetManifest.AudioAsset.Id"/>. Also the record's file stem in the store.
    /// </summary>
    public required string AssetId { get; init; }

    /// <summary>
    /// `20` §2.1's tool + version, or null. Required on an audio record and forbidden on an art
    /// one — see <see cref="AudioTooling"/>.
    /// </summary>
    public required AudioTooling? Tooling { get; init; }

    /// <summary>The discriminator, as written in the record's <c>kind</c> member.</summary>
    public abstract string Kind { get; }

    /// <summary>
    /// Every generation tool this record names, for the `20` §6 licence check. Empty where the
    /// record names none (a procedural record's "tool" is this repository).
    /// </summary>
    public abstract IEnumerable<string> ToolsNamed { get; }
}

/// <summary>
/// `20` §2.1's <em>"(tool, version, prompt, date) for every generated file"</em> — the two members
/// of that tuple the art record has no place for.
/// </summary>
/// <remarks>
/// 🔒 Required on an audio record, and forbidden on an art one. An art record's tool is named by
/// its <see cref="ProvenanceRecord.Kind"/> (`15` §B0 locks Midjourney) plus, for Midjourney, its
/// own <see cref="MidjourneyProvenance.ModelVersion"/>; a second tool field there would be two
/// sources of truth for one fact, and the day they disagreed neither would be evidence of
/// anything. <see cref="RecordValidator"/> enforces both directions.
/// </remarks>
/// <param name="Tool">The tool's name, e.g. <c>Audacity</c>.</param>
/// <param name="Version">The tool's version string, verbatim as the tool reports it.</param>
public sealed record AudioTooling(string Tool, string Version);

/// <summary>
/// `15` §B0 — an asset generated by Midjourney. The field set is §B0's, verbatim.
/// </summary>
/// <remarks>
/// Every parameter is a <see cref="string"/> rather than a parsed number, including
/// <see cref="Seed"/> and <see cref="Stylize"/>. A provenance record is evidence of what was run,
/// so it stores what the tool reported; parsing <c>--s 250</c> into an <c>int</c> and writing it
/// back would silently normalise a value nobody may alter after the fact.
/// </remarks>
public sealed record MidjourneyProvenance : ProvenanceRecord
{
    /// <summary>The `15` §B0 discriminator value.</summary>
    public const string KindName = "midjourney";

    /// <summary>§B0's job ID.</summary>
    public required string JobId { get; init; }

    /// <summary>The full positive prompt, §B1 scaffold included.</summary>
    public required string Prompt { get; init; }

    /// <summary>§B0's seed, verbatim.</summary>
    public required string Seed { get; init; }

    /// <summary>§B0's <c>--sref</c> style-reference value.</summary>
    public required string Sref { get; init; }

    /// <summary>§B0's <c>--ar</c>.</summary>
    public required string AspectRatio { get; init; }

    /// <summary>§B0's <c>--style</c> (the doc locks <c>raw</c>).</summary>
    public required string Style { get; init; }

    /// <summary>§B0's <c>--s</c> stylize value.</summary>
    public required string Stylize { get; init; }

    /// <summary>The model version the job ran on.</summary>
    public required string ModelVersion { get; init; }

    /// <summary>§B0's date, ISO-8601 <c>YYYY-MM-DD</c>.</summary>
    public required string Date { get; init; }

    /// <inheritdoc/>
    public override string Kind => KindName;

    /// <inheritdoc/>
    public override IEnumerable<string> ToolsNamed =>
        Tooling is null ? [KindName] : [KindName, Tooling.Tool];
}

/// <summary>
/// Code-drawn output: M8-10's placeholders, and the procedural in-engine VFX the O8 ruling
/// substituted for `15` §E19's 32 sprite sheets.
/// </summary>
/// <remarks>
/// 🔒 <see cref="RepoCommit"/> stands where §B0 puts the job id and the seed. For generated art
/// the reproducibility anchor is the job; for code-drawn art it is the revision of the generator,
/// and a job id or a seed field here would be a hole waiting for a plausible value (steering S6).
/// There is no date member for the same reason: no design document authorises one, and the commit
/// already dates the output.
/// </remarks>
public sealed record ProceduralProvenance : ProvenanceRecord
{
    /// <summary>The discriminator value.</summary>
    public const string KindName = "procedural";

    /// <summary>The generator that drew it, e.g. a tool assembly name.</summary>
    public required string Generator { get; init; }

    /// <summary>The full 40-hex commit of this repository at the time it was drawn.</summary>
    public required string RepoCommit { get; init; }

    /// <summary>The generator's parameters. May be empty; may not be null.</summary>
    public required IReadOnlyDictionary<string, string> Parameters { get; init; }

    /// <inheritdoc/>
    public override string Kind => KindName;

    /// <summary>
    /// 🔒 Empty for a procedural art record: the "tool" is this repository, which needs no
    /// commercial licence confirmed in writing. An audio one still names its editing tool.
    /// </summary>
    public override IEnumerable<string> ToolsNamed =>
        Tooling is null ? [] : [Tooling.Tool];
}

/// <summary>
/// A CC0 asset taken from a library — `20` §2 contemplates exactly this for ~20 UI sounds.
/// </summary>
public sealed record Cc0Provenance : ProvenanceRecord
{
    /// <summary>The discriminator value.</summary>
    public const string KindName = "cc0";

    /// <summary>The pack or library it came from.</summary>
    public required string Source { get; init; }

    /// <summary>The URL it was retrieved from.</summary>
    public required string Url { get; init; }

    /// <summary>The licence text or SPDX identifier, e.g. <c>CC0-1.0</c>.</summary>
    public required string Licence { get; init; }

    /// <summary>The retrieval date, ISO-8601 <c>YYYY-MM-DD</c>.</summary>
    public required string DateRetrieved { get; init; }

    /// <inheritdoc/>
    public override string Kind => KindName;

    /// <summary>
    /// 🔒 The pack is not a generation tool: its terms are carried by <see cref="Licence"/> on
    /// the record itself, which is what a CC0 dedication is. Only the editing tool, where one was
    /// used, needs a `20` §6 confirmation.
    /// </summary>
    public override IEnumerable<string> ToolsNamed =>
        Tooling is null ? [] : [Tooling.Tool];
}
