using Shouldly;
using SlayIdleRepeat.Core.Model.Snapshots;
using Xunit;

namespace SlayIdleRepeat.Core.Tests.Model.Snapshots;

/// <summary>
/// 🔒 The committed reference-vector table of `14` §16.6, asserted row by row.
/// </summary>
/// <remarks>
/// <b>A failure here is a determinism break, never a test fix.</b> The rows were generated by an
/// independent transcription of §16.6's table, whose FNV-1a 64 first reproduced Noll's published
/// vectors. If a row moves, every <c>stateHash</c> ever issued to a client moved with it, every client
/// mirror stops agreeing with the server, and the parity and reconnect tests start comparing fiction.
/// This is the table the cross-platform determinism job re-asserts on each runtime.
/// </remarks>
public sealed class CanonicalStateWriterReferenceVectorTests
{
    /// <summary>Every committed row: the value encodes to exactly the committed bytes.</summary>
    [Theory]
    [MemberData(nameof(CanonicalIds))]
    public void CanonicalBytes_matches_every_committed_reference_vector(string rowId)
    {
        var row = CanonicalReferenceVectors.Row(rowId);

        var hex = Convert.ToHexString(BytesFor(row)).ToLowerInvariant();

        hex.ShouldBe(row.EncodedHex, $"'{row.Id}' pins {row.Why}");
    }

    /// <summary>
    /// Every committed row's byte length is exactly the committed length. Asserted alongside the
    /// bytes because it localises a break: a length mismatch says the shape moved, a same-length
    /// mismatch says a value did.
    /// </summary>
    [Theory]
    [MemberData(nameof(CanonicalIds))]
    public void The_canonical_encoding_matches_every_committed_byte_length(string rowId)
    {
        var row = CanonicalReferenceVectors.Row(rowId);

        BytesFor(row).Length.ShouldBe(row.EncodedByteLength, $"'{row.Id}' pins {row.Why}");
    }

    /// <summary>Every committed row: those bytes hash to exactly the committed 64-bit value.</summary>
    [Theory]
    [MemberData(nameof(CanonicalIds))]
    public void Fnv1a64_matches_every_committed_reference_vector(string rowId)
    {
        var row = CanonicalReferenceVectors.Row(rowId);

        var hash = CanonicalStateWriter.Fnv1a64(BytesFor(row));

        hash.ShouldBe(row.Hash, $"'{row.Id}' pins {row.Why}");
    }

    /// <summary>
    /// Every committed <c>meta</c> row, through the public door the game actually calls. The three
    /// assertions above pin the internals; this one pins that the published API still agrees.
    /// </summary>
    [Theory]
    [MemberData(nameof(MetaRowIds))]
    public void HashMetaCommandState_matches_every_committed_meta_reference_vector(string rowId)
    {
        var row = CanonicalReferenceVectors.Row(rowId);

        var wire = CanonicalStateWriter.HashMetaCommandState(ReferenceSnapshots.Instance(row.Id));

        wire.ShouldBe(row.Wire, $"'{row.Id}' pins {row.Why}");
    }

    /// <summary>Every committed <c>run</c> row, through the two-snapshot public entry point.</summary>
    [Theory]
    [MemberData(nameof(RunRowIds))]
    public void HashRunCommandState_matches_every_committed_run_reference_vector(string rowId)
    {
        var row = CanonicalReferenceVectors.Row(rowId);

        var wire = CanonicalStateWriter.HashRunCommandState(
            ReferenceSnapshots.Instance(row.Id), ReferenceSnapshots.SecondInstance(row.Id));

        wire.ShouldBe(row.Wire, $"'{row.Id}' pins {row.Why}");
    }

    /// <summary>
    /// The table guards the code; this guards the table. A future edit that quietly dropped the
    /// only negative-int row, or the only multi-byte string, would leave a suite that still
    /// passes while covering less — the failure a pinned table is least able to announce.
    /// </summary>
    [Theory]
    [InlineData("scalars-all")]
    [InlineData("int-negative-one")]
    [InlineData("bool-true")]
    [InlineData("string-multibyte")]
    [InlineData("string-null")]
    [InlineData("double-rounded")]
    [InlineData("double-positive-zero")]
    [InlineData("timestamp-2024")]
    [InlineData("timestamp-pre-epoch")]
    [InlineData("optional-present")]
    [InlineData("optional-absent")]
    [InlineData("nested-depth-three")]
    [InlineData("list-stored-order")]
    [InlineData("list-of-records")]
    [InlineData("dictionary-string-keys")]
    [InlineData("dictionary-numeric-keys")]
    [InlineData("meta-command-player-only")]
    [InlineData("run-command-player-then-run")]
    [InlineData("wire-leading-zero-nibbles")]
    public void The_reference_table_still_covers_every_load_bearing_rule(string rowId)
    {
        CanonicalReferenceVectors.Canonical
            .Where(row => row.Id == rowId).ShouldHaveSingleItem();
    }

    /// <summary>Both hashing modes are represented — a table with one mode pins half the contract.</summary>
    [Theory]
    [InlineData("meta")]
    [InlineData("run")]
    public void The_reference_table_still_covers_both_hashing_modes(string mode)
    {
        CanonicalReferenceVectors.Canonical.Where(row => row.Mode == mode).ShouldNotBeEmpty();
    }

    /// <summary>
    /// Rows the encoding must keep apart have different committed hashes. Pinned as pairs so the
    /// table itself carries the property, rather than two unrelated constants that happen to differ.
    /// </summary>
    [Theory]
    [InlineData("list-stored-order", "list-reversed")]
    [InlineData("nested-lists-ambiguity-a", "nested-lists-ambiguity-b")]
    [InlineData("string-empty", "string-null")]
    [InlineData("optional-present-zero", "optional-absent")]
    [InlineData("run-command-player-then-run", "run-command-swapped")]
    [InlineData("meta-command-player-only", "run-command-player-then-run")]
    public void Rows_the_encoding_must_keep_apart_have_different_committed_hashes(string firstId, string secondId)
    {
        var first = CanonicalReferenceVectors.Row(firstId);
        var second = CanonicalReferenceVectors.Row(secondId);

        first.Hash.ShouldNotBe(second.Hash);
        CanonicalStateWriter.Fnv1a64(BytesFor(first)).ShouldNotBe(CanonicalStateWriter.Fnv1a64(BytesFor(second)));
    }

    private static byte[] BytesFor(CanonicalReferenceVectors.CanonicalRow row) =>
        row.Mode == "run"
            ? CanonicalStateWriter.CanonicalBytes(ReferenceSnapshots.Instance(row.Id))
                .Concat(CanonicalStateWriter.CanonicalBytes(ReferenceSnapshots.SecondInstance(row.Id)))
                .ToArray()
            : CanonicalStateWriter.CanonicalBytes(ReferenceSnapshots.Instance(row.Id));

    public static TheoryData<string> CanonicalIds() => CanonicalReferenceVectors.CanonicalIds();

    public static TheoryData<string> MetaRowIds() => CanonicalReferenceVectors.CanonicalIds("meta");

    public static TheoryData<string> RunRowIds() => CanonicalReferenceVectors.CanonicalIds("run");
}
