using FluentAssertions;
using SlayIdleRepeat.Core.Model.Snapshots;
using Xunit;

namespace SlayIdleRepeat.Core.Tests.Model.Snapshots;

/// <summary>
/// 🔒 The committed reference-vector table of `14` §16.6, asserted row by row.
/// </summary>
/// <remarks>
/// <para>
/// <b>A failure here is a determinism break, never a test fix.</b> The rows live in
/// <c>Model/Snapshots/CanonicalStateWriterReferenceVectors.json</c> and were generated by an
/// independent transcription of the §16.6 specification table, whose FNV-1a 64 first reproduced
/// Landon Curt Noll's published vectors. If a row moves, every <c>stateHash</c> ever issued to a
/// client moved with it, every client mirror stops agreeing with the server, and the parity and
/// reconnect chaos tests (§13) start comparing fiction.
/// </para>
/// <para>
/// This is the table the cross-platform determinism job (`14` §8.2, task M5-12) re-asserts on
/// Linux x64, Android ARM64 and iOS ARM64, alongside <c>Rng/Hash64ReferenceVectors.json</c>.
/// </para>
/// </remarks>
public sealed class CanonicalStateWriterReferenceVectorTests
{
    /// <summary>Every committed row: the value encodes to exactly the committed bytes.</summary>
    [Theory]
    [MemberData(nameof(CanonicalIds))]
    public void CanonicalBytes_matches_every_committed_reference_vector(string rowId)
    {
        var row = CanonicalReferenceVectors.Row(rowId);

        var hex = Convert.ToHexString(BytesFor(row)).ToLowerInvariant();

        hex.Should().Be(row.EncodedHex, "'{0}' pins {1}", row.Id, row.Why);
    }

    /// <summary>
    /// Every committed row's byte length is exactly the committed length. Asserted alongside the
    /// bytes because it localises a break: a length mismatch says the shape moved, a same-length
    /// mismatch says a value did.
    /// </summary>
    [Theory]
    [MemberData(nameof(CanonicalIds))]
    public void The_canonical_encoding_matches_every_committed_byte_length(string rowId)
    {
        var row = CanonicalReferenceVectors.Row(rowId);

        BytesFor(row).Should().HaveCount(row.EncodedByteLength, "'{0}' pins {1}", row.Id, row.Why);
    }

    /// <summary>Every committed row: those bytes hash to exactly the committed 64-bit value.</summary>
    [Theory]
    [MemberData(nameof(CanonicalIds))]
    public void Fnv1a64_matches_every_committed_reference_vector(string rowId)
    {
        var row = CanonicalReferenceVectors.Row(rowId);

        var hash = CanonicalStateWriter.Fnv1a64(BytesFor(row));

        hash.Should().Be(row.Hash, "'{0}' pins {1}", row.Id, row.Why);
    }

    /// <summary>
    /// Every committed <c>meta</c> row, through the public door the game actually calls. The three
    /// assertions above pin the internals; this one pins that the published API still agrees.
    /// </summary>
    [Theory]
    [MemberData(nameof(MetaRowIds))]
    public void HashMetaCommandState_matches_every_committed_meta_reference_vector(string rowId)
    {
        var row = CanonicalReferenceVectors.Row(rowId);

        var wire = CanonicalStateWriter.HashMetaCommandState(ReferenceSnapshots.Instance(row.Id));

        wire.Should().Be(row.Wire, "'{0}' pins {1}", row.Id, row.Why);
    }

    /// <summary>Every committed <c>run</c> row, through the two-snapshot public entry point.</summary>
    [Theory]
    [MemberData(nameof(RunRowIds))]
    public void HashRunCommandState_matches_every_committed_run_reference_vector(string rowId)
    {
        var row = CanonicalReferenceVectors.Row(rowId);

        var wire = CanonicalStateWriter.HashRunCommandState(
            ReferenceSnapshots.Instance(row.Id), ReferenceSnapshots.SecondInstance(row.Id));

        wire.Should().Be(row.Wire, "'{0}' pins {1}", row.Id, row.Why);
    }

    /// <summary>
    /// The table guards the code; this guards the table. A future edit that quietly dropped the
    /// only negative-int row, or the only multi-byte string, would leave a suite that still
    /// passes while covering less — the failure a pinned table is least able to announce.
    /// </summary>
    [Theory]
    [InlineData("scalars-all")]
    [InlineData("int-negative-one")]
    [InlineData("bool-true")]
    [InlineData("string-multibyte")]
    [InlineData("string-null")]
    [InlineData("double-rounded")]
    [InlineData("double-negative-zero")]
    [InlineData("timestamp-2024")]
    [InlineData("timestamp-pre-epoch")]
    [InlineData("optional-present")]
    [InlineData("optional-absent")]
    [InlineData("nested-depth-three")]
    [InlineData("list-stored-order")]
    [InlineData("list-of-records")]
    [InlineData("dictionary-string-keys")]
    [InlineData("dictionary-numeric-keys")]
    [InlineData("meta-command-player-only")]
    [InlineData("run-command-player-then-run")]
    [InlineData("wire-leading-zero-nibbles")]
    public void The_reference_table_still_covers_every_load_bearing_rule(string rowId)
    {
        CanonicalReferenceVectors.Canonical
            .Should().ContainSingle(row => row.Id == rowId);
    }

    /// <summary>Row ids identify a row in a failure message; duplicates make that a lie.</summary>
    [Fact]
    public void The_reference_table_ids_are_unique()
    {
        CanonicalReferenceVectors.Canonical.Select(row => row.Id).Should().OnlyHaveUniqueItems();
    }

    /// <summary>Both hashing modes are represented — a table with one mode pins half the contract.</summary>
    [Theory]
    [InlineData("meta")]
    [InlineData("run")]
    public void The_reference_table_still_covers_both_hashing_modes(string mode)
    {
        CanonicalReferenceVectors.Canonical.Where(row => row.Mode == mode).Should().NotBeEmpty();
    }

    /// <summary>
    /// Rows the encoding must keep apart have different committed hashes. Pinned as pairs so the
    /// table itself carries the property, rather than two unrelated constants that happen to differ.
    /// </summary>
    [Theory]
    [InlineData("list-stored-order", "list-reversed")]
    [InlineData("nested-lists-ambiguity-a", "nested-lists-ambiguity-b")]
    [InlineData("string-empty", "string-null")]
    [InlineData("optional-present-zero", "optional-absent")]
    [InlineData("double-negative-zero", "double-positive-zero")]
    [InlineData("run-command-player-then-run", "run-command-swapped")]
    [InlineData("meta-command-player-only", "run-command-player-then-run")]
    public void Rows_the_encoding_must_keep_apart_have_different_committed_hashes(string firstId, string secondId)
    {
        var first = CanonicalReferenceVectors.Row(firstId);
        var second = CanonicalReferenceVectors.Row(secondId);

        first.Hash.Should().NotBe(second.Hash);
        CanonicalStateWriter.Fnv1a64(BytesFor(first)).Should().NotBe(CanonicalStateWriter.Fnv1a64(BytesFor(second)));
    }

    /// <summary>
    /// The committed wire string of every row is the committed hash, rendered. The two columns are
    /// redundant on purpose — a row whose <c>wire</c> and <c>hash</c> disagree is a corrupt row,
    /// and that is worth catching in the table rather than in a consumer.
    /// </summary>
    [Theory]
    [MemberData(nameof(CanonicalIds))]
    public void Every_committed_row_renders_its_own_hash(string rowId)
    {
        var row = CanonicalReferenceVectors.Row(rowId);

        row.Wire.Should().Be("fnv1a:" + row.Hash.ToString("x16", System.Globalization.CultureInfo.InvariantCulture));
    }

    /// <summary>Every row carries a reason, so a failing row explains what it was defending.</summary>
    [Theory]
    [MemberData(nameof(CanonicalIds))]
    public void Every_committed_row_says_what_it_pins(string rowId)
    {
        CanonicalReferenceVectors.Row(rowId).Why.Should().NotBeNullOrWhiteSpace();
    }

    private static byte[] BytesFor(CanonicalReferenceVectors.CanonicalRow row) =>
        row.Mode == "run"
            ? CanonicalStateWriter.CanonicalBytes(ReferenceSnapshots.Instance(row.Id))
                .Concat(CanonicalStateWriter.CanonicalBytes(ReferenceSnapshots.SecondInstance(row.Id)))
                .ToArray()
            : CanonicalStateWriter.CanonicalBytes(ReferenceSnapshots.Instance(row.Id));

    public static TheoryData<string> CanonicalIds() => CanonicalReferenceVectors.CanonicalIds();

    public static TheoryData<string> MetaRowIds() => CanonicalReferenceVectors.CanonicalIds("meta");

    public static TheoryData<string> RunRowIds() => CanonicalReferenceVectors.CanonicalIds("run");
}
