using System.Globalization;
using System.Text.Json;
using Xunit;

namespace SlayIdleRepeat.Core.Tests.Model.Snapshots;

/// <summary>
/// Reads <c>CanonicalStateWriterReferenceVectors.json</c> — the committed determinism pin of
/// `14` §16.6 — out of this assembly's embedded resources.
/// </summary>
/// <remarks>
/// The rows in that file were generated by an independent Python transcription of the §16.6
/// specification table, whose FNV-1a 64 first reproduced Landon Curt Noll's published vectors.
/// They are the expectations, not the output of the code under test. Nothing here re-derives a
/// hash or a byte: it only parses.
/// </remarks>
internal static class CanonicalReferenceVectors
{
    private const string ResourceName =
        "SlayIdleRepeat.Core.Tests.Model.Snapshots.CanonicalStateWriterReferenceVectors.json";

    private static readonly JsonDocument Document = Load();

    /// <summary>Landon Curt Noll's published FNV-1a 64 vectors — the external check.</summary>
    internal static IReadOnlyList<PublishedRow> Published { get; } = ReadPublished();

    /// <summary>Rows over the canonical encoding of `14` §16.6.</summary>
    internal static IReadOnlyList<CanonicalRow> Canonical { get; } = ReadCanonical();

    /// <summary>The FNV-1a 64 offset basis the committed file names.</summary>
    internal static ulong OffsetBasis { get; } = ParseHex(
        Document.RootElement.GetProperty("fnv1a64PublishedKnownAnswerVectors")
            .GetProperty("offsetBasis").GetString()!);

    /// <summary>The FNV-1a 64 prime the committed file names.</summary>
    internal static ulong Prime { get; } = ParseHex(
        Document.RootElement.GetProperty("fnv1a64PublishedKnownAnswerVectors")
            .GetProperty("prime").GetString()!);

    /// <summary>The one canonical row with this id.</summary>
    internal static CanonicalRow Row(string id) =>
        Canonical.Single(row => row.Id.Equals(id, StringComparison.Ordinal));

    /// <summary>Every canonical row id, as xUnit theory data.</summary>
    internal static TheoryData<string> CanonicalIds()
    {
        var data = new TheoryData<string>();
        foreach (var row in Canonical)
        {
            data.Add(row.Id);
        }

        return data;
    }

    /// <summary>Every published FNV-1a vector, as xUnit theory data.</summary>
    internal static TheoryData<string, ulong> PublishedRows()
    {
        var data = new TheoryData<string, ulong>();
        foreach (var row in Published)
        {
            data.Add(row.Input, row.Hash);
        }

        return data;
    }

    private static JsonDocument Load()
    {
        using var stream = typeof(CanonicalReferenceVectors).Assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException(
                $"The determinism pin '{ResourceName}' is not embedded in " +
                $"{typeof(CanonicalReferenceVectors).Assembly.GetName().Name}. Available: " +
                string.Join(", ", typeof(CanonicalReferenceVectors).Assembly.GetManifestResourceNames()));

        return JsonDocument.Parse(stream);
    }

    private static ulong ParseHex(string text) =>
        ulong.Parse(text.AsSpan(2), NumberStyles.HexNumber, CultureInfo.InvariantCulture);

    private static IReadOnlyList<PublishedRow> ReadPublished() =>
        Document.RootElement
            .GetProperty("fnv1a64PublishedKnownAnswerVectors")
            .GetProperty("rows")
            .EnumerateArray()
            .Select(element => new PublishedRow(
                element.GetProperty("input").GetString()!,
                ParseHex(element.GetProperty("hash").GetString()!)))
            .ToArray();

    private static IReadOnlyList<CanonicalRow> ReadCanonical() =>
        Document.RootElement
            .GetProperty("canonicalStateVectors")
            .GetProperty("rows")
            .EnumerateArray()
            .Select(element => new CanonicalRow(
                element.GetProperty("id").GetString()!,
                element.GetProperty("why").GetString()!,
                element.GetProperty("mode").GetString()!,
                element.GetProperty("encodedByteLength").GetInt32(),
                element.GetProperty("encodedHex").GetString()!,
                ParseHex(element.GetProperty("hash").GetString()!),
                element.GetProperty("wire").GetString()!))
            .ToArray();

    /// <summary>One published FNV-1a 64 known-answer vector over raw UTF-8 bytes.</summary>
    internal sealed record PublishedRow(string Input, ulong Hash);

    /// <summary>One committed canonical-encoding row.</summary>
    internal sealed record CanonicalRow(
        string Id,
        string Why,
        string Mode,
        int EncodedByteLength,
        string EncodedHex,
        ulong Hash,
        string Wire);
}
