using System.Globalization;
using System.Text.Json;
using Xunit;

namespace SlayIdleRepeat.Core.Tests.Rules.Combat;

/// <summary>
/// Reads <c>CombatLogReferenceVectors.json</c> — the committed <c>LogHash</c> determinism pin of
/// `05` §7 — out of this assembly's embedded resources.
/// </summary>
/// <remarks>
/// The rows were generated by an independent Python transcription of `14` §16.6's encoding table
/// and `05` §7's field list, whose FNV-1a 64 first reproduced Landon Curt Noll's published vectors.
/// They are the expectations, not the output of the code under test — nothing here re-derives a
/// hash or a byte, it only parses.
/// </remarks>
internal static class CombatLogReferenceVectors
{
    private const string ResourceName =
        "SlayIdleRepeat.Core.Tests.Rules.Combat.CombatLogReferenceVectors.json";

    private static readonly JsonDocument Document = Load();

    /// <summary>Landon Curt Noll's published FNV-1a 64 vectors — the external check.</summary>
    internal static IReadOnlyList<PublishedRow> Published { get; } = ReadPublished();

    /// <summary>Rows over the canonical encoding of a combat-event list.</summary>
    internal static IReadOnlyList<LogRow> Rows { get; } = ReadRows();

    /// <summary>The FNV-1a 64 offset basis the committed file names.</summary>
    internal static ulong OffsetBasis { get; } = ParseHex(
        Document.RootElement.GetProperty("fnv1a64PublishedKnownAnswerVectors")
            .GetProperty("offsetBasis").GetString()!);

    /// <summary>The FNV-1a 64 prime the committed file names.</summary>
    internal static ulong Prime { get; } = ParseHex(
        Document.RootElement.GetProperty("fnv1a64PublishedKnownAnswerVectors")
            .GetProperty("prime").GetString()!);

    /// <summary>The one row with this id.</summary>
    internal static LogRow Row(string id) =>
        Rows.Single(row => row.Id.Equals(id, StringComparison.Ordinal));

    /// <summary>Every row id, as xUnit theory data.</summary>
    internal static TheoryData<string> RowIds()
    {
        var data = new TheoryData<string>();
        foreach (var row in Rows)
        {
            data.Add(row.Id);
        }

        return data;
    }

    /// <summary>Every published FNV-1a vector, as xUnit theory data.</summary>
    internal static TheoryData<string, ulong> PublishedRows()
    {
        var data = new TheoryData<string, ulong>();
        foreach (var row in Published)
        {
            data.Add(row.Input, row.Hash);
        }

        return data;
    }

    private static JsonDocument Load()
    {
        using var stream = typeof(CombatLogReferenceVectors).Assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException(
                $"The LogHash determinism pin '{ResourceName}' is not embedded in " +
                $"{typeof(CombatLogReferenceVectors).Assembly.GetName().Name}. Available: " +
                string.Join(", ", typeof(CombatLogReferenceVectors).Assembly.GetManifestResourceNames()));

        return JsonDocument.Parse(stream);
    }

    private static ulong ParseHex(string text) =>
        ulong.Parse(text.AsSpan(2), NumberStyles.HexNumber, CultureInfo.InvariantCulture);

    private static IReadOnlyList<PublishedRow> ReadPublished() =>
        Document.RootElement
            .GetProperty("fnv1a64PublishedKnownAnswerVectors")
            .GetProperty("rows")
            .EnumerateArray()
            .Select(element => new PublishedRow(
                element.GetProperty("input").GetString()!,
                ParseHex(element.GetProperty("hash").GetString()!)))
            .ToArray();

    private static IReadOnlyList<LogRow> ReadRows() =>
        Document.RootElement
            .GetProperty("combatLogVectors")
            .GetProperty("rows")
            .EnumerateArray()
            .Select(element => new LogRow(
                element.GetProperty("id").GetString()!,
                element.GetProperty("why").GetString()!,
                element.GetProperty("eventCount").GetInt32(),
                element.GetProperty("encodedByteLength").GetInt32(),
                element.GetProperty("encodedHex").GetString()!,
                ParseHex(element.GetProperty("hash").GetString()!)))
            .ToArray();

    /// <summary>One published FNV-1a 64 known-answer vector over raw UTF-8 bytes.</summary>
    internal sealed record PublishedRow(string Input, ulong Hash);

    /// <summary>One committed combat-log row.</summary>
    internal sealed record LogRow(
        string Id,
        string Why,
        int EventCount,
        int EncodedByteLength,
        string EncodedHex,
        ulong Hash);
}
