using System.Globalization;

namespace SlayIdleRepeat.Core.Tests;

/// <summary>
/// 🔒 The `14` §8.1 / `30` §3 <c>CommandSeed</c> invariant, as a mechanism: <b>a command carries a
/// server-issued <c>CommandSeed</c> exactly when it draws out-of-run randomness, and
/// <c>GameContext.CommandSeed</c> is <c>null</c> on every other command.</b>
/// </summary>
/// <remarks>
/// <para>
/// Two regimes (`14` §8.1, restated in `30` §3). <b>Run draws</b> are
/// <c>Hash64(runSeed, stream, i)</c> off the <c>Run</c> aggregate's committed seed and its
/// persisted per-stream counters — state, not ambience — so <c>CommandSeed</c> is not involved and
/// must be <c>null</c>. <b>Meta draws</b> are <c>Hash64(CommandSeed, stream, i)</c> from
/// <c>i = 0</c>, with no persisted counter; the command is atomic and idempotency replays its
/// stored outcome, so a meta draw can never be re-rolled by resubmission. The seed is generated by
/// the server host, never by the domain.
/// </para>
/// <para>
/// ⚠️ <b>The subject set is empty today.</b> M1-02 authors the commands; M1-07 authors only
/// <see cref="GameContext"/>. So the rule over the real vocabulary
/// (<c>Every_seed_bearing_command_name_names_a_real_command_type</c>) holds vacuously, exactly the
/// way <c>Model/Snapshots/SnapshotFieldOrderPin</c> does, with no <c>Skip</c> and nothing to
/// remember to switch on. <see cref="Violations"/> itself is <b>not</b> vacuous: it is driven
/// directly by the tests over the nine names below, so the classifier's teeth are proven before
/// there is anything to apply them to.
/// </para>
/// </remarks>
internal static class CommandSeedPin
{
    /// <summary>What a violation means, said plainly, so a failure is not "fixed" in the test.</summary>
    internal const string Consequence =
        "CommandSeed is server-issued and META-ONLY (14 §8.1, 30 §3). The domain never invents " +
        "entropy: an in-run draw comes from the Run aggregate's committed runSeed and its persisted " +
        "per-stream counter, and a meta draw comes from this seed at i = 0 with no counter. Fix the " +
        "composition root that built the context, never this rule.";

    /// <summary>
    /// 🔒 The nine meta commands that draw randomness and therefore carry a <c>CommandSeed</c>.
    /// </summary>
    /// <remarks>
    /// Fixed by the M1 kickoff (2026-08-11), which froze the command vocabulary at 49 — 19 run
    /// commands, all carrying <c>null</c>, and 30 meta commands of which exactly these nine draw.
    /// <c>BEGIN_SESSION</c>'s draw is the day's quest slate and Daily shop block (`30` §2.3);
    /// <c>SPIN_WHEEL</c>, the three container opens and the two item rerolls are `30` §3's
    /// "wheel spins, container opens"; <c>START_DUEL</c> is the PvP ghost draw (`11` §6).
    /// <b>The 19 run-command names are deliberately not enumerated here</b> — they are M1-02's to
    /// author, and writing a plausible list would be inventing vocabulary.
    /// </remarks>
    internal static IReadOnlySet<string> SeedBearingMetaCommands { get; } =
        new HashSet<string>(StringComparer.Ordinal)
        {
            "BEGIN_SESSION",
            "REROLL_QUEST",
            "SPIN_WHEEL",
            "REFORGE_ITEM",
            "RETUNE_ITEM",
            "OPEN_CHEST",
            "OPEN_EGG",
            "OPEN_CRATE",
            "START_DUEL",
        };

    /// <summary>The namespace `30` §11.4 reserves for the command vocabulary. Empty until M1-02.</summary>
    internal const string CommandsNamespace = "SlayIdleRepeat.Core.Commands";

    /// <summary>
    /// Every <b>concrete</b> non-nested command type. Empty until M1-02 lands the vocabulary.
    /// </summary>
    /// <remarks>
    /// <para>
    /// 🔒 <b>Concrete, and the filter is a sharpening rather than a weakening.</b> M1-06 landed the
    /// abstract <c>GameCommand</c> base and nothing else, which is the whole point of that task
    /// landing first: <c>Every_command_type_is_handled_by_Apply</c> fails the build for any concrete
    /// subtype no dispatch row names, so the base must exist before the vocabulary does. A base with
    /// no wire name and no seed is not a command anybody sends — `14` §2.3's registry is 49 named
    /// rows — and counting it here would have woken this file's rules over a vocabulary of one
    /// abstraction. The architecture suite draws the same line in the same place
    /// (<c>!t.IsAbstract</c>).
    /// </para>
    /// <para>
    /// 🔒 <b>The independent backstop, named exactly.</b> <c>SubjectSetFloorTests</c> in the
    /// architecture suite tracks <c>SlayIdleRepeat.Core.Commands</c> as LIVE from M1-06, which
    /// watches that the <em>namespace</em> exists — it went live the moment the abstract base landed
    /// and therefore says nothing about whether a command type has arrived. What announces the
    /// arrival independently of this file is
    /// <c>Commands.GameCommandTests.The_command_vocabulary_is_still_absent_and_says_so_when_it_arrives</c>,
    /// which quantifies over concrete <c>GameCommand</c> subtypes <em>wherever</em> they are
    /// declared, and <c>DomainPurityTests.Every_command_type_is_handled_by_Apply</c>, which reads
    /// the assembly with Mono.Cecil and sees internal types. The two subject sets overlap without
    /// being the same — a command declared outside this namespace wakes those and not this one —
    /// which is the point of having both.
    /// </para>
    /// </remarks>
    internal static IReadOnlyList<Type> CommandTypes { get; } = ConcreteTypesUnder(CommandsNamespace);

    /// <summary>
    /// Every non-nested, non-abstract type declared in <c>Core</c> under a namespace or below it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Exposed rather than inlined so the self-tests can prove this half is not the vacuity source:
    /// pointed at a namespace that exists today it must reach something, or
    /// <see cref="CommandTypes"/> would stay empty for the wrong reason on the day M1-02 lands.
    /// </para>
    /// <para>
    /// ⚠️ Accessibility is deliberately <b>not</b> filtered. <c>Core</c> grants
    /// <c>InternalsVisibleTo</c> to this assembly (`30` §11.3) and `30` §11.2 makes handlers and
    /// rules internal, so an internal or file-scoped command vocabulary is entirely plausible — and
    /// an <c>IsPublic</c> filter would silence the rule that quantifies over this set <em>and</em>
    /// the tripwire that announces it, together, on the same accessibility choice.
    /// </para>
    /// </remarks>
    internal static IReadOnlyList<Type> ConcreteTypesUnder(string namespacePrefix) =>
        typeof(GameContext).Assembly
            .GetTypes()
            .Where(t => !t.IsNested && !t.IsAbstract)
            .Where(t => IsUnder(t.Namespace, namespacePrefix))
            .OrderBy(t => t.Name, StringComparer.Ordinal)
            .ToArray();

    /// <summary>True when <paramref name="candidate"/> is <paramref name="prefix"/> or below it.</summary>
    internal static bool IsUnder(string? candidate, string prefix) =>
        candidate is not null &&
        (candidate.Equals(prefix, StringComparison.Ordinal) ||
         candidate.StartsWith(prefix + ".", StringComparison.Ordinal));

    /// <summary>
    /// 🔒 The `14` §2.3 wire name a command type <b>declares</b>, or <c>null</c> when no dispatch
    /// row names the type.
    /// </summary>
    /// <remarks>
    /// <para>
    /// 🔒 <b>Read, not guessed — and that is a change of kind rather than of implementation</b>
    /// (carried-forward item 4, closed by M1-06). This method used to be a documented <em>heuristic</em>:
    /// strip a <c>Command</c> suffix, split on the capitals, upper-case the lot, so
    /// <c>SpinWheelCommand</c> became <c>SPIN_WHEEL</c> — and <c>OpenPvPCommand</c> became
    /// <c>OPEN_PV_P</c>, a known limit it could only pin rather than fix. It existed because no
    /// authored scheme did. M1-06's dispatch table declares the wire name beside the command's
    /// handler and its kind, so there is now a scheme to read, and a heuristic beside it would be a
    /// second answer to a question that has one (steering <b>S4</b>).
    /// </para>
    /// <para>
    /// ⚠️ A type that declares no row answers <c>null</c> rather than a name. That is not this
    /// file's failure to report: <c>DomainPurityTests.Every_command_type_is_handled_by_Apply</c>
    /// fails the build for a concrete command no dispatch row names, and duplicating the complaint
    /// here would be a second mechanism for one rule.
    /// </para>
    /// </remarks>
    /// <param name="commandType">A concrete <c>GameCommand</c> subtype.</param>
    /// <exception cref="ArgumentNullException"><paramref name="commandType"/> is null.</exception>
    internal static string? WireNameOf(Type commandType)
    {
        ArgumentNullException.ThrowIfNull(commandType);

        return GameRules.RegistrationFor(commandType)?.WireName;
    }

    /// <summary>
    /// 🔒 The invariant itself: everything wrong with pairing <paramref name="commandName"/> with
    /// <paramref name="context"/>'s <c>CommandSeed</c>. Empty means the pairing is legal.
    /// </summary>
    /// <remarks>
    /// The two failures carry distinct wording on purpose (steering S2): "a run command was handed
    /// a seed" and "a meta draw was handed none" are opposite defects with opposite fixes, and a
    /// test that pinned only "it failed" would pass while the wrong one fired.
    /// </remarks>
    internal static IReadOnlyList<string> Violations(string commandName, GameContext context)
    {
        ArgumentNullException.ThrowIfNull(commandName);
        ArgumentNullException.ThrowIfNull(context);

        var draws = SeedBearingMetaCommands.Contains(commandName);

        if (draws && context.CommandSeed is null)
        {
            return new[]
            {
                $"{commandName} draws out-of-run randomness, so GameContext.CommandSeed must carry " +
                $"the server-issued seed — it is null. {Consequence}",
            };
        }

        if (!draws && context.CommandSeed is not null)
        {
            return new[]
            {
                $"{commandName} draws no out-of-run randomness, so GameContext.CommandSeed must be " +
                $"null — it is {context.CommandSeed.Value.ToString(CultureInfo.InvariantCulture)}. " +
                Consequence,
            };
        }

        return Array.Empty<string>();
    }
}
